### ISSUE TITLE
还在维护吗？

### ISSUE THREAD

**Issue by HRxiaohu** [Edint386/github-webhooks-to-kook#3]
全网只剩这一个github机器人了QAQ
希望可以添加Actions失败推送，新ISSUE和PR推送
辛苦作者大大了

**Comment by Edint386** [comment]
在的，先画个饼，不知道什么时候能做出来（

**Comment by Edint386** [comment]
俺也是python萌新 回头再看看文档

**Comment by HRxiaohu** [comment]
好的好的~感谢作者大大！
