### ISSUE TITLE
github actions并未启用

### ISSUE THREAD

**Issue by axiangcoding** [Edint386/github-webhooks-to-kook#7]
请看是否需要配置什么权限

**Comment by Edint386** [comment]
抱歉抱歉才看到，但是好像看了一圈也没什么问题，不知道为啥不跑

**Comment by axiangcoding** [comment]
> 抱歉抱歉才看到，但是好像看了一圈也没什么问题，不知道为啥不跑

啊，没关系了其实，我这边也没在用其实..只是提一下这个问题
